import os

DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///payments.db")
MAX_RETRY_ATTEMPTS = 3
PAYMENT_TIMEOUT_SECONDS = 30
SUPPORTED_CURRENCIES = ["USD", "EUR", "GBP", "CAD"]
FRAUD_THRESHOLD = 10000.00
RATE_LIMIT_PER_MINUTE = 100
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")
